Feature/list keys pix
stone-co/go-stone-openbank pull request #40
Opened 2021-11-12 04:54 UTC by gmarcial

### Description:

The endpoints of PIX key utilize of idempotency key to making idempotent requests.

In the project, other endpoints were utilizing the same behavior, I took this opportunity to refactor and encapsulate this in the creation of a request.

---

### Issue: 
[List keys pix](https://github.com/stone-co/go-stone-openbank/issues/38)

---

### Evidence:

I tested the listing of the pix keys and other endpoints affected with the refactoring of the idempotency key.

![evidence](https://user-images.githubusercontent.com/17557482/140255623-f7344167-907b-4cbb-8103-afb8b0c0360e.png)

### Note:

The name of property referent to PIX key status of it is different, in the docs is key_status, but in response is status.

Beyond other data that are not in the documentation, but I only followed the documentation.

![more-data](https://user-images.githubusercontent.com/17557482/140256217-7fbb9d11-6975-40bf-984d-f642aa8b4321.png)

2021-11-12 04:56 UTC, gmarcial commented
Was applied the what was proposed in code-review

@guilhermebr @Streppel

2021-11-18 20:44 UTC, guilhermebr requested changes

2021-11-18 20:44 UTC, guilhermebr commented on payment_invoice.go
> +	req, err := s.client.NewAPIRequest(http.MethodPost, path,nil)
```suggestion
	req, err := s.client.NewAPIRequest(http.MethodPost, path, nil)
```

2021-11-19 02:17 UTC, gmarcial commented on payment_invoice.go
> +	req, err := s.client.NewAPIRequest(http.MethodPost, path,nil)
Feito @guilhermebr!

2021-12-04 21:16 UTC, guilhermebr approved these changes

2021-12-07 18:31 UTC, merged